# To install postgresql on a dev box run
# `brew install postgres`
#
# follow instructions on how to create a database
#
# `rake db:migrate db:seed_fu spec` should set up the databases
# to manually setup a database `createdb -h localhost fairest_development`
#
# To manually start/stop postgres use the following aliases
#
# alias pgstart='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
# alias pgstop=' pg_ctl -D /usr/local/var/postgres stop -s -m fast'
#

common: &common
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: dlikhten

development:
  <<: *common
  database: fairest_development

test:
  <<: *common
  database: fairest_test


production:
  adapter: postgresql
  database: fairest_production.postgres
  pool: 5
  timeout: 5000
